query GetService($id: ID!){
  service(id:$id){
    activation
    activationNumber
    deactivation
    category {
      id
    }
    description
    view
    like
    help
    isFeatured
    name
    operator {
      id
    }
    operatorId
    categoryId
    thumb1x
    price
    status
    typeId
    tags
    runmode
  }
  operators {
    id
    name
  }
  categories {
    id
    name
  }
  serviceTypes {
    id
    name
 }
}
