query GetService($ID: ID!){
  service(id:$ID){
    activation
    activationNumber
    deactivation
    category {
      id
    }
    description
    view
    like
    help
    isFeatured
    name
    operator {
      id
    }
    operatorId
    categoryId
    thumb
    price
    status
    typeId
    tags
  }
  operators {
    id
    name
  }
  categories {
    id
    name
  }
  serviceTypes {
    id
    name
 }
}
