query LatestServices($typeId: ID, $operatorId: ID){
  latestServices(typeId: $typeId, operatorId: $operatorId){
    id
    name
    description
    original
    thumb
 		view
    isFeatured
    type {
      id
      name
    }
  }
  serviceTypes {
    id
    name
    count
  }
  operators {
    id
    name
  }
}
