query LatestServices(
 $typeId: ID,
 $operatorId: ID,
 $page: Int,
 ){
 latestServices(
 typeId: $typeId,
 operatorId: $operatorId,
 page: $page,
  ){
    id
    name
    description
    original
    thumb1x
 		view
    isFeatured
  
    type {
      id
      name
    }
  }
  serviceTypes {
    id
    name
    count
  }
  operators {
    id
    name
  }
}
