{
  operators {
    id
    name
    credit
    internetCharge
    payBill
    buyCharge
  }
  categories {
    id
    name
  }
  serviceTypes {
    id
    name
    nameEng
    hasOperator
    hasSubCat
 }
}
